name : Automate build, test, deploy of the app

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and deploy of the app
    runs-on: ubuntu-latest
    steps:

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Aptos-Hackathon/Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}-aptos:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Aptos-Hackathon/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}-aptos:latest